create table Employee_Client(EmployeeNumber int,EmployeeFirstName varchar(25),EmployeeSecondName varchar(25),EmployeeCity varchar(25));
insert into Employee_Client values(1,"Virat","Kohli","Delhi");
insert into Employee_Client values(2,"Rohit","Sharma","Mumbai");
insert into Employee_Client values(3,"Raina","Iyer","Chennai");
insert into Employee_Client values(4,"Vybav","Krishna","Chennai");
insert into Employee_Client values(5,"Suresh","Yadav","Mumbai");
insert into Employee_Client values(6,"Ramesh","Varma","Chennai");
insert into Employee_Client values(7,"Prakash","Gowda","Delhi");
insert into Employee_Client values(8,"Manish","Kumar","Bengaluru");
insert into Employee_Client values(9,"Harish","Pandya","Mumbai");
insert into Employee_Client values(10,"Natarajan","Narayan","Chennai");
insert into Employee_Client values(11,"Vikram","Rathour","Kolkata");